// Generated by https://quicktype.io

export interface LoginResponse {
    IdCanilla: string;
    Token:     string;
}


export interface loginData {
    mail: string,
    clave: string,
}


export interface registerData {
    token:     string,
    idCanilla: string,
    clave:     string,
    apellido:  string,
    nombre:    string,
    direccion: string,
    codPostal: string,
    localidad: string,
    celular:   string,
    paquete:   string,
}


export interface forgotPass {
    mail: string,
}



