// Generated by https://quicktype.io

export interface OrdersData {
    CantidadReposiciones: number;
    HojaActual:           number;
    reposiciones:         Reposicione[];
}

export interface Reposicione {
    IdCanilla:          string;
    FechaCreacion:      string;
    PrecioTotal:        number;
    PrecioUnidad:       number;
    IdReposicion:       number;
    Estado:             string;
    Titulo:             string;
    CantidadSolicitada: number;
    CantidadAsignada:   number;
    Familia:            string;
    Edicion:            number;
    Autor:              string;
}
