// Generated by https://quicktype.io

export interface TipoProductosData {
    IdTipoProducto: number;
    Descripcion:    string;
}


// Generated by https://quicktype.io

export interface FamiliasProductoData {
    IdProductoLogistica: string;
    Descripcion:         string;
}


// Generated by https://quicktype.io
export interface AutorProductData {
    Autor: string[],
}


// Generated by https://quicktype.io

export interface ProductoData {
    IdProductoLogistica: string;
    Familia:             string;
    Autor:               string;
    Edicion:             number;
    FechaCirculacion:    string;
    Descripcion:         string;
    Precio:              number;
    URLImagen:           string;
}


